In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import seaborn as sns
import pandas_profiling
%matplotlib inline

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/DA Project/bank-additional-full.csv',sep=';')
df

       age          job  marital  ... euribor3m nr.employed    y
0       56    housemaid  married  ...     4.857      5191.0   no
1       57     services  married  ...     4.857      5191.0   no
2       37     services  married  ...     4.857      5191.0   no
3       40       admin.  married  ...     4.857      5191.0   no
4       56     services  married  ...     4.857      5191.0   no
...    ...          ...      ...  ...       ...         ...  ...
41183   73      retired  married  ...     1.028      4963.6  yes
41184   46  blue-collar  married  ...     1.028      4963.6   no
41185   56      retired  married  ...     1.028      4963.6   no
41186   44   technician  married  ...     1.028      4963.6  yes
41187   74      retired  married  ...     1.028      4963.6   no

[41188 rows x 21 columns]

In [ ]:
del df['duration']

In [ ]:
cols_num = ['campaign', 'pdays',
       'previous', 'emp.var.rate', 'cons.price.idx','cons.conf.idx', 'nr.employed','age','euribor3m']

In [ ]:
cols_cat = ['job', 'marital', 
       'education', 'default',
       'housing', 'loan', 'contact', 'month',
       'day_of_week', 'poutcome']

In [ ]:
df[cols_cat]
cols_new_cat=pd.get_dummies(df[cols_cat],drop_first = False)
cols_new_cat.head()

   job_admin.  job_blue-collar  ...  poutcome_nonexistent  poutcome_success
0           0                0  ...                     1                 0
1           0                0  ...                     1                 0
2           0                0  ...                     1                 0
3           1                0  ...                     1                 0
4           0                0  ...                     1                 0

[5 rows x 53 columns]

In [ ]:
df_z_scaled = df[cols_num].copy()
df_z_scaled

       campaign  pdays  previous  ...  nr.employed  age  euribor3m
0             1    999         0  ...       5191.0   56      4.857
1             1    999         0  ...       5191.0   57      4.857
2             1    999         0  ...       5191.0   37      4.857
3             1    999         0  ...       5191.0   40      4.857
4             1    999         0  ...       5191.0   56      4.857
...         ...    ...       ...  ...          ...  ...        ...
41183         1    999         0  ...       4963.6   73      1.028
41184         1    999         0  ...       4963.6   46      1.028
41185         2    999         0  ...       4963.6   56      1.028
41186         1    999         0  ...       4963.6   44      1.028
41187         3    999         1  ...       4963.6   74      1.028

[41188 rows x 9 columns]

In [ ]:
# copy the data
  
# apply normalization techniques
for column in df_z_scaled.columns:
    df_z_scaled[column] = (df_z_scaled[column] -
                           df_z_scaled[column].mean()) / df_z_scaled[column].std()    
  
# view normalized data   
display(df_z_scaled)

       campaign     pdays  previous  ...  nr.employed       age  euribor3m
0     -0.565915  0.195412 -0.349490  ...     0.331676  1.533016   0.712451
1     -0.565915  0.195412 -0.349490  ...     0.331676  1.628973   0.712451
2     -0.565915  0.195412 -0.349490  ...     0.331676 -0.290182   0.712451
3     -0.565915  0.195412 -0.349490  ...     0.331676 -0.002309   0.712451
4     -0.565915  0.195412 -0.349490  ...     0.331676  1.533016   0.712451
...         ...       ...       ...  ...          ...       ...        ...
41183 -0.565915  0.195412 -0.349490  ...    -2.815662  3.164298  -1.495168
41184 -0.565915  0.195412 -0.349490  ...    -2.815662  0.573438  -1.495168
41185 -0.204906  0.195412 -0.349490  ...    -2.815662  1.533016  -1.495168
41186 -0.565915  0.195412 -0.349490  ...    -2.815662  0.381522  -1.495168
41187  0.156103  0.195412  1.671116  ...    -2.815662  3.260256  -1.495168

[41188 rows x 9 columns]

In [ ]:
cols_all_cat=list(cols_new_cat.columns)

In [ ]:
df = pd.concat([df_z_scaled,cols_new_cat], axis = 1)
df

       campaign     pdays  ...  poutcome_nonexistent  poutcome_success
0     -0.565915  0.195412  ...                     1                 0
1     -0.565915  0.195412  ...                     1                 0
2     -0.565915  0.195412  ...                     1                 0
3     -0.565915  0.195412  ...                     1                 0
4     -0.565915  0.195412  ...                     1                 0
...         ...       ...  ...                   ...               ...
41183 -0.565915  0.195412  ...                     1                 0
41184 -0.565915  0.195412  ...                     1                 0
41185 -0.204906  0.195412  ...                     1                 0
41186 -0.565915  0.195412  ...                     1                 0
41187  0.156103  0.195412  ...                     0                 0

[41188 rows x 62 columns]

In [ ]:
df1=pd.read_csv('/content/drive/MyDrive/DA Project/bank-additional-full.csv',sep=';')

In [ ]:
del df1['duration']

In [ ]:
df=pd.concat([df,df1['y']], axis = 1)

In [ ]:
df.groupby('y').size()

y
no     36548
yes     4640
dtype: int64

In [ ]:
df['y'] = (df.y == 'yes').astype('int')

In [ ]:
df.groupby('y').size()

y
0    36548
1     4640
dtype: int64

In [ ]:
from collections import Counter
from sklearn.datasets import make_classification
from matplotlib import pyplot
from numpy import where
y = df['y']
X = df.values[:, :-1]
counter = Counter(y)
print(counter)

Counter({0: 36548, 1: 4640})

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,random_state=50)

In [ ]:
Counter(y_test)

Counter({0: 10964, 1: 1393})

In [ ]:
Counter(y_train)

Counter({0: 25584, 1: 3247})

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE(sampling_strategy=0.5) #oversampling minority class to 50% of majority class

In [ ]:
X_train_smote , y_train_smote = smote.fit_resample(X_train,y_train)

In [ ]:
Counter(y_train_smote)

Counter({0: 25584, 1: 12792})

In [ ]:
# Import `Sequential` from `keras.models`
from keras.models import Sequential

# Import `Dense` from `keras.layers`
from keras.layers import Dense

# Initialize the constructor
model = Sequential()

# Add an input layer 
model.add(Dense(50, activation='relu', input_shape=(62,)))

# Add one hidden layer 
model.add(Dense(200, activation='relu'))
model.add(Dense(50, activation='relu'))

# Add an output layer 
model.add(Dense(1, activation='sigmoid'))

In [ ]:
from keras import backend as K

def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc',f1_m,precision_m, recall_m])

In [ ]:
model.fit(X_train_smote,y_train_smote,epochs = 125)

Epoch 1/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.4756 - acc: 0.7950 - f1_m: 0.6309 - precision_m: 0.7615 - recall_m: 0.5607
Epoch 2/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.4417 - acc: 0.8059 - f1_m: 0.6545 - precision_m: 0.7781 - recall_m: 0.5851
Epoch 3/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.4119 - acc: 0.8186 - f1_m: 0.6851 - precision_m: 0.7863 - recall_m: 0.6291
Epoch 4/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.3797 - acc: 0.8340 - f1_m: 0.7228 - precision_m: 0.7844 - recall_m: 0.6913
Epoch 5/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.3510 - acc: 0.8480 - f1_m: 0.7543 - precision_m: 0.7929 - recall_m: 0.7384
Epoch 6/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.3245 - acc: 0.8618 - f1_m: 0.7796 - precision_m: 0.8057 - recall_m: 0.7728
Epoch 7/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.3031 - acc: 0.8721 - f1_m: 0.8008 - precision_m: 0.8177 - recall_m: 0.8019
Epoch 8/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.2856 - acc: 0.8805 - f1_m: 0.8117 - precision_m: 0.8256 - recall_m: 0.8142
Epoch 9/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.2708 - acc: 0.8883 - f1_m: 0.8245 - precision_m: 0.8362 - recall_m: 0.8299
Epoch 10/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.2550 - acc: 0.8953 - f1_m: 0.8364 - precision_m: 0.8478 - recall_m: 0.8405
Epoch 11/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.2421 - acc: 0.9011 - f1_m: 0.8450 - precision_m: 0.8513 - recall_m: 0.8532
Epoch 12/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.2302 - acc: 0.9072 - f1_m: 0.8545 - precision_m: 0.8616 - recall_m: 0.8619
Epoch 13/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.2209 - acc: 0.9118 - f1_m: 0.8621 - precision_m: 0.8667 - recall_m: 0.8717
Epoch 14/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.2103 - acc: 0.9138 - f1_m: 0.8643 - precision_m: 0.8686 - recall_m: 0.8722
Epoch 15/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.2015 - acc: 0.9191 - f1_m: 0.8731 - precision_m: 0.8754 - recall_m: 0.8826
Epoch 16/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1936 - acc: 0.9227 - f1_m: 0.8784 - precision_m: 0.8817 - recall_m: 0.8870
Epoch 17/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1861 - acc: 0.9253 - f1_m: 0.8833 - precision_m: 0.8852 - recall_m: 0.8924
Epoch 18/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1785 - acc: 0.9285 - f1_m: 0.8880 - precision_m: 0.8906 - recall_m: 0.8970
Epoch 19/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1736 - acc: 0.9297 - f1_m: 0.8908 - precision_m: 0.8928 - recall_m: 0.8998
Epoch 20/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1664 - acc: 0.9336 - f1_m: 0.8960 - precision_m: 0.8969 - recall_m: 0.9050
Epoch 21/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1619 - acc: 0.9350 - f1_m: 0.8982 - precision_m: 0.8988 - recall_m: 0.9081
Epoch 22/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1576 - acc: 0.9369 - f1_m: 0.9011 - precision_m: 0.9026 - recall_m: 0.9089
Epoch 23/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1515 - acc: 0.9414 - f1_m: 0.9080 - precision_m: 0.9089 - recall_m: 0.9170
Epoch 24/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1430 - acc: 0.9430 - f1_m: 0.9101 - precision_m: 0.9111 - recall_m: 0.9183
Epoch 25/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1419 - acc: 0.9432 - f1_m: 0.9120 - precision_m: 0.9125 - recall_m: 0.9203
Epoch 26/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1370 - acc: 0.9450 - f1_m: 0.9138 - precision_m: 0.9147 - recall_m: 0.9216
Epoch 27/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1338 - acc: 0.9466 - f1_m: 0.9154 - precision_m: 0.9168 - recall_m: 0.9231
Epoch 28/125
1200/1200 [==============================] - 4s 4ms/step - loss: 0.1283 - acc: 0.9496 - f1_m: 0.9197 - precision_m: 0.9215 - recall_m: 0.9266
Epoch 29/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1255 - acc: 0.9495 - f1_m: 0.9201 - precision_m: 0.9208 - recall_m: 0.9276
Epoch 30/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1202 - acc: 0.9526 - f1_m: 0.9261 - precision_m: 0.9241 - recall_m: 0.9353
Epoch 31/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1208 - acc: 0.9525 - f1_m: 0.9253 - precision_m: 0.9270 - recall_m: 0.9312
Epoch 32/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1184 - acc: 0.9541 - f1_m: 0.9286 - precision_m: 0.9302 - recall_m: 0.9347
Epoch 33/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1171 - acc: 0.9542 - f1_m: 0.9285 - precision_m: 0.9313 - recall_m: 0.9331
Epoch 34/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1086 - acc: 0.9577 - f1_m: 0.9342 - precision_m: 0.9356 - recall_m: 0.9391
Epoch 35/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1077 - acc: 0.9577 - f1_m: 0.9329 - precision_m: 0.9341 - recall_m: 0.9386
Epoch 36/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.1075 - acc: 0.9572 - f1_m: 0.9319 - precision_m: 0.9335 - recall_m: 0.9369
Epoch 37/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1017 - acc: 0.9599 - f1_m: 0.9365 - precision_m: 0.9377 - recall_m: 0.9420
Epoch 38/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.1032 - acc: 0.9593 - f1_m: 0.9352 - precision_m: 0.9350 - recall_m: 0.9421
Epoch 39/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0992 - acc: 0.9610 - f1_m: 0.9389 - precision_m: 0.9400 - recall_m: 0.9435
Epoch 40/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0985 - acc: 0.9604 - f1_m: 0.9382 - precision_m: 0.9389 - recall_m: 0.9438
Epoch 41/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0952 - acc: 0.9621 - f1_m: 0.9402 - precision_m: 0.9419 - recall_m: 0.9444
Epoch 42/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0954 - acc: 0.9614 - f1_m: 0.9388 - precision_m: 0.9403 - recall_m: 0.9436
Epoch 43/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0958 - acc: 0.9632 - f1_m: 0.9417 - precision_m: 0.9432 - recall_m: 0.9466
Epoch 44/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0873 - acc: 0.9667 - f1_m: 0.9478 - precision_m: 0.9484 - recall_m: 0.9521
Epoch 45/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0907 - acc: 0.9644 - f1_m: 0.9444 - precision_m: 0.9441 - recall_m: 0.9503
Epoch 46/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0890 - acc: 0.9642 - f1_m: 0.9428 - precision_m: 0.9447 - recall_m: 0.9467
Epoch 47/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0858 - acc: 0.9652 - f1_m: 0.9448 - precision_m: 0.9465 - recall_m: 0.9485
Epoch 48/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0879 - acc: 0.9660 - f1_m: 0.9466 - precision_m: 0.9467 - recall_m: 0.9521
Epoch 49/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0858 - acc: 0.9658 - f1_m: 0.9458 - precision_m: 0.9467 - recall_m: 0.9501
Epoch 50/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0848 - acc: 0.9664 - f1_m: 0.9473 - precision_m: 0.9479 - recall_m: 0.9522
Epoch 51/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0832 - acc: 0.9671 - f1_m: 0.9486 - precision_m: 0.9499 - recall_m: 0.9527
Epoch 52/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0823 - acc: 0.9681 - f1_m: 0.9492 - precision_m: 0.9505 - recall_m: 0.9534
Epoch 53/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0830 - acc: 0.9677 - f1_m: 0.9488 - precision_m: 0.9502 - recall_m: 0.9530
Epoch 54/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0772 - acc: 0.9700 - f1_m: 0.9528 - precision_m: 0.9546 - recall_m: 0.9557
Epoch 55/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0825 - acc: 0.9681 - f1_m: 0.9500 - precision_m: 0.9494 - recall_m: 0.9556
Epoch 56/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0795 - acc: 0.9695 - f1_m: 0.9514 - precision_m: 0.9526 - recall_m: 0.9552
Epoch 57/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0783 - acc: 0.9695 - f1_m: 0.9525 - precision_m: 0.9523 - recall_m: 0.9579
Epoch 58/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0775 - acc: 0.9704 - f1_m: 0.9532 - precision_m: 0.9541 - recall_m: 0.9571
Epoch 59/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0748 - acc: 0.9713 - f1_m: 0.9544 - precision_m: 0.9543 - recall_m: 0.9588
Epoch 60/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0740 - acc: 0.9713 - f1_m: 0.9548 - precision_m: 0.9544 - recall_m: 0.9597
Epoch 61/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0764 - acc: 0.9705 - f1_m: 0.9534 - precision_m: 0.9543 - recall_m: 0.9573
Epoch 62/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0765 - acc: 0.9711 - f1_m: 0.9548 - precision_m: 0.9557 - recall_m: 0.9584
Epoch 63/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0734 - acc: 0.9720 - f1_m: 0.9561 - precision_m: 0.9572 - recall_m: 0.9596
Epoch 64/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0721 - acc: 0.9724 - f1_m: 0.9562 - precision_m: 0.9560 - recall_m: 0.9609
Epoch 65/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0712 - acc: 0.9726 - f1_m: 0.9569 - precision_m: 0.9584 - recall_m: 0.9598
Epoch 66/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0710 - acc: 0.9733 - f1_m: 0.9578 - precision_m: 0.9583 - recall_m: 0.9614
Epoch 67/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0710 - acc: 0.9733 - f1_m: 0.9580 - precision_m: 0.9589 - recall_m: 0.9616
Epoch 68/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0708 - acc: 0.9733 - f1_m: 0.9579 - precision_m: 0.9567 - recall_m: 0.9638
Epoch 69/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0685 - acc: 0.9742 - f1_m: 0.9600 - precision_m: 0.9600 - recall_m: 0.9640
Epoch 70/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0703 - acc: 0.9722 - f1_m: 0.9566 - precision_m: 0.9552 - recall_m: 0.9620
Epoch 71/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0669 - acc: 0.9739 - f1_m: 0.9591 - precision_m: 0.9596 - recall_m: 0.9629
Epoch 72/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0677 - acc: 0.9730 - f1_m: 0.9571 - precision_m: 0.9563 - recall_m: 0.9621
Epoch 73/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0701 - acc: 0.9730 - f1_m: 0.9570 - precision_m: 0.9579 - recall_m: 0.9606
Epoch 74/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0657 - acc: 0.9750 - f1_m: 0.9608 - precision_m: 0.9613 - recall_m: 0.9641
Epoch 75/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0656 - acc: 0.9750 - f1_m: 0.9608 - precision_m: 0.9617 - recall_m: 0.9638
Epoch 76/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0662 - acc: 0.9744 - f1_m: 0.9597 - precision_m: 0.9596 - recall_m: 0.9637
Epoch 77/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0637 - acc: 0.9758 - f1_m: 0.9619 - precision_m: 0.9610 - recall_m: 0.9668
Epoch 78/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0651 - acc: 0.9755 - f1_m: 0.9614 - precision_m: 0.9615 - recall_m: 0.9651
Epoch 79/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0627 - acc: 0.9761 - f1_m: 0.9627 - precision_m: 0.9628 - recall_m: 0.9663
Epoch 80/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0654 - acc: 0.9747 - f1_m: 0.9601 - precision_m: 0.9598 - recall_m: 0.9644
Epoch 81/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0624 - acc: 0.9757 - f1_m: 0.9621 - precision_m: 0.9622 - recall_m: 0.9657
Epoch 82/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0618 - acc: 0.9762 - f1_m: 0.9624 - precision_m: 0.9628 - recall_m: 0.9657
Epoch 83/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0629 - acc: 0.9754 - f1_m: 0.9614 - precision_m: 0.9620 - recall_m: 0.9647
Epoch 84/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0605 - acc: 0.9765 - f1_m: 0.9626 - precision_m: 0.9628 - recall_m: 0.9663
Epoch 85/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0621 - acc: 0.9760 - f1_m: 0.9622 - precision_m: 0.9620 - recall_m: 0.9661
Epoch 86/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0621 - acc: 0.9762 - f1_m: 0.9629 - precision_m: 0.9636 - recall_m: 0.9657
Epoch 87/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0596 - acc: 0.9775 - f1_m: 0.9645 - precision_m: 0.9638 - recall_m: 0.9689
Epoch 88/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0624 - acc: 0.9763 - f1_m: 0.9626 - precision_m: 0.9630 - recall_m: 0.9661
Epoch 89/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0614 - acc: 0.9769 - f1_m: 0.9640 - precision_m: 0.9644 - recall_m: 0.9667
Epoch 90/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0602 - acc: 0.9765 - f1_m: 0.9630 - precision_m: 0.9623 - recall_m: 0.9673
Epoch 91/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0604 - acc: 0.9761 - f1_m: 0.9620 - precision_m: 0.9614 - recall_m: 0.9662
Epoch 92/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0571 - acc: 0.9786 - f1_m: 0.9657 - precision_m: 0.9660 - recall_m: 0.9691
Epoch 93/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0597 - acc: 0.9772 - f1_m: 0.9638 - precision_m: 0.9633 - recall_m: 0.9681
Epoch 94/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0564 - acc: 0.9786 - f1_m: 0.9668 - precision_m: 0.9672 - recall_m: 0.9697
Epoch 95/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0618 - acc: 0.9755 - f1_m: 0.9609 - precision_m: 0.9612 - recall_m: 0.9645
Epoch 96/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0594 - acc: 0.9774 - f1_m: 0.9645 - precision_m: 0.9643 - recall_m: 0.9684
Epoch 97/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0565 - acc: 0.9783 - f1_m: 0.9660 - precision_m: 0.9646 - recall_m: 0.9706
Epoch 98/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0583 - acc: 0.9780 - f1_m: 0.9649 - precision_m: 0.9642 - recall_m: 0.9691
Epoch 99/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0562 - acc: 0.9780 - f1_m: 0.9650 - precision_m: 0.9637 - recall_m: 0.9697
Epoch 100/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0589 - acc: 0.9769 - f1_m: 0.9635 - precision_m: 0.9635 - recall_m: 0.9671
Epoch 101/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0563 - acc: 0.9788 - f1_m: 0.9665 - precision_m: 0.9657 - recall_m: 0.9706
Epoch 102/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0565 - acc: 0.9784 - f1_m: 0.9659 - precision_m: 0.9658 - recall_m: 0.9696
Epoch 103/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0569 - acc: 0.9784 - f1_m: 0.9662 - precision_m: 0.9673 - recall_m: 0.9686
Epoch 104/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0548 - acc: 0.9796 - f1_m: 0.9679 - precision_m: 0.9682 - recall_m: 0.9709
Epoch 105/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0549 - acc: 0.9796 - f1_m: 0.9678 - precision_m: 0.9678 - recall_m: 0.9712
Epoch 106/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0558 - acc: 0.9787 - f1_m: 0.9651 - precision_m: 0.9655 - recall_m: 0.9682
Epoch 107/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0554 - acc: 0.9788 - f1_m: 0.9669 - precision_m: 0.9668 - recall_m: 0.9703
Epoch 108/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0520 - acc: 0.9800 - f1_m: 0.9690 - precision_m: 0.9690 - recall_m: 0.9720
Epoch 109/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0560 - acc: 0.9787 - f1_m: 0.9666 - precision_m: 0.9662 - recall_m: 0.9705
Epoch 110/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0537 - acc: 0.9789 - f1_m: 0.9662 - precision_m: 0.9659 - recall_m: 0.9696
Epoch 111/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0529 - acc: 0.9799 - f1_m: 0.9684 - precision_m: 0.9688 - recall_m: 0.9713
Epoch 112/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0531 - acc: 0.9801 - f1_m: 0.9678 - precision_m: 0.9682 - recall_m: 0.9706
Epoch 113/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0532 - acc: 0.9791 - f1_m: 0.9672 - precision_m: 0.9675 - recall_m: 0.9703
Epoch 114/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0556 - acc: 0.9783 - f1_m: 0.9661 - precision_m: 0.9669 - recall_m: 0.9689
Epoch 115/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0511 - acc: 0.9802 - f1_m: 0.9688 - precision_m: 0.9685 - recall_m: 0.9723
Epoch 116/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0542 - acc: 0.9789 - f1_m: 0.9670 - precision_m: 0.9671 - recall_m: 0.9704
Epoch 117/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0517 - acc: 0.9804 - f1_m: 0.9685 - precision_m: 0.9677 - recall_m: 0.9726
Epoch 118/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0524 - acc: 0.9797 - f1_m: 0.9684 - precision_m: 0.9685 - recall_m: 0.9713
Epoch 119/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0505 - acc: 0.9804 - f1_m: 0.9689 - precision_m: 0.9684 - recall_m: 0.9728
Epoch 120/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0528 - acc: 0.9799 - f1_m: 0.9682 - precision_m: 0.9676 - recall_m: 0.9719
Epoch 121/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0508 - acc: 0.9802 - f1_m: 0.9691 - precision_m: 0.9688 - recall_m: 0.9724
Epoch 122/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0529 - acc: 0.9792 - f1_m: 0.9673 - precision_m: 0.9671 - recall_m: 0.9709
Epoch 123/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0522 - acc: 0.9798 - f1_m: 0.9682 - precision_m: 0.9681 - recall_m: 0.9715
Epoch 124/125
1200/1200 [==============================] - 4s 3ms/step - loss: 0.0505 - acc: 0.9808 - f1_m: 0.9693 - precision_m: 0.9682 - recall_m: 0.9735
Epoch 125/125
1200/1200 [==============================] - 3s 3ms/step - loss: 0.0505 - acc: 0.9804 - f1_m: 0.9680 - precision_m: 0.9682 - recall_m: 0.9710

In [ ]:
predict_x=model.predict(X_test) 
classes_x=np.argmax(predict_x,axis=1)

In [ ]:
predict_x

array([[2.2570051e-12],
       [3.8565066e-08],
       [2.6336312e-04],
       ...,
       [9.8666942e-01],
       [9.9999964e-01],
       [4.8110691e-05]], dtype=float32)

In [ ]:
yhat=[]
for i in predict_x:
  if i[0]>0.60:
    yhat.append(1)
  else:
    yhat.append(0)
ytest=list(y_test)

In [ ]:
import sklearn.metrics
sklearn.metrics.precision_recall_fscore_support(ytest,yhat,average='binary')

(0.31353135313531355, 0.34099066762383345, 0.3266850068775791, None)

In [ ]:
sklearn.metrics.accuracy_score(ytest,yhat)

0.8415473011248685

In [ ]:
Counter(y_test)

Counter({0: 10964, 1: 1393})

In [ ]:
Counter(ytest)

Counter({0: 10964, 1: 1393})

In [ ]:
Counter(y_train_smote)

Counter({0: 25584, 1: 5116})